### ISSUE TITLE
fix loading of JSON if it is empty

### ISSUE THREAD

**Issue by eobrien16** [soopreme/PresDense#1]
`SyntaxError: /Users/s0lr/Documents/PresDense/API/profiles.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:673:27)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Promise (/Users/s0lr/Documents/PresDense/API/functions/loadProfiles.js:4:28)
    at new Promise (<anonymous>)
    at Object.module.exports.file [as loadProfiles] (/Users/s0lr/Documents/PresDense/API/functions/loadProfiles.js:2:26)`

**Comment by eobrien16** [comment]
JSON now contains an empty array
